spring.application.name=ApiRestSwagger
springdoc.swagger-ui.path=/docs
spring.datasource.url=jdbc:postgresql://localhost/db_api_product
spring.datasource.username=root
spring.datasource.password=santiMysql_7
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
server.port=8080

# Nivel de log por paquete
logging.level.root=INFO
logging.level.com.santiagomarin=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Archivo de log
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

# Patron de logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n
# Habilitar colores en consola
spring.output.ansi.enabled=ALWAYS
# Formato mas bonito
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}